### ISSUE TITLE
GitLab API privileges

### ISSUE THREAD

**Issue by simplelife2010** [nbedos/cistern#21]
Is it really necessary to require a full API privileged GitLab token? I might only want to read the jobs status and logs. For security reasons, it would be nice to use a less privileged token.

**Comment by nbedos** [comment]
Unfortunately `cistern` requires a personal access token with the `api` scope because that is the least privileged scope that gives access to API endpoints under `/projects` (which is the only way to get information about repositories and pipelines).

All possible scopes of GitLab personal access tokens are documented [here](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html#limiting-scopes-of-a-personal-access-token). `read_user` is unsuitable for `cistern` because API endpoints under `/users` do not give access to projects or pipelines. `read_registry`, `read_repository`, `write_repository` do not give access to the API at all. `api` gives full read and write access to the API and `sudo` is even more privileged than `api`. So `api` is currently the least bad choice.

However [this issue](https://gitlab.com/gitlab-org/gitlab/issues/35067#new-scopes) will add a `read_api` scope to GitLab 12.9 so the situation will eventually improve. I expect `cistern` to be compatible with this new scope without any modification.

**Comment by simplelife2010** [comment]
Thanks, this answer is 100% acceptable.
