### ISSUE TITLE
Azure builds not showing on PR branches

### ISSUE THREAD

**Issue by Cadair** [nbedos/cistern#25]
It seems that no Azure builds are currently showing up on branches from my fork to the upstream repo. The circleci builds are working fine.

**Comment by nbedos** [comment]
Thanks for reporting this issue. I'm able to reproduce it by running `cistern -r https://github.com/sunpy/sunpy aa283cd` where `aa283cd` is a commit from https://github.com/sunpy/sunpy/pull/3740.

It seems that the pipeline returned by the Azure API has a `sourceVersion` attribute set to `7d7a347836c67b4cc26110c98d062e5dad8e69f7` when I expected it to be `aa283cda023c2c1a652bd1a13f3fbe24a35a1a84` (the hash of your commit). I'll have to look further into this.

**Comment by nbedos** [comment]
This should be fixed on https://github.com/nbedos/cistern/tree/bugfix/azure_missing_build_in_pr

However there's a lot work to do in order to have a nice, working integration between `cistern` and pull requests. I was honestly more surprised to see that it did work for Circle CI than to see that it did not work with Azure. I'm also pretty sure that for now `cistern` doesn't work with merge requests on GitLab.

**Comment by Cadair** [comment]
My initial testing indicates this is working, I will let you know how it goes over a few more branches etc.

**Comment by nbedos** [comment]
Thanks for the feedback. These changes are now merged in `master`.
